services:
  - type: web
    name: vnuchok
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: VNUCHOK_DEMO_MODE
        value: "1"
      - key: VNUCHOK_SECRET_KEY
        generateValue: true
    autoDeploy: true
    healthCheckPath: /health
